### ISSUE TITLE
Missing Northwind database in App_Data?

### ISSUE THREAD

**Issue by bartvanderwal** [telerik/kendoui-northwind-dashboard#1]
The app is showing 'NO DATA' when run after first install. It actually show the app handles missing data pretty nicely, no stack trace, but ofcours I want to be able to see the demo locally. See screenshot below!

Notes: I see in Visual Studio that the `App_Data` folder is showing a missing `Northwind.mdf` and `Northwind_log.ldf' (in Solution Explorer). The actual file is only visible when you use the ' Show all files' icon, and is named 'NORTHWND.MDF' (e.g. in caps, but mainly with a`I`less then the file stored in the`.sln`file). There is no`.ldf`, but that seems to be somehow contained within the`.mdf`file. But after including the 'NORTHWND.MDF' in the solution it still doesn't work. The connectionstring in the`web.config`points correctly: ...`AttachDbFilename=|DataDirectory|\NORTHWND.mdf` ...

Note: I just installed a Kendo trial, installed it into Visual Studio 2013 and cloned this project from Github. No other changes.

![nodataavailable](https://cloud.githubusercontent.com/assets/3029472/4676499/0266d9b4-55dc-11e4-9f78-507e44b9c819.png)

**Comment by Shloosh** [comment]
If anyone is using SQLEXPRESS 2014, change the Data Source in the connection string from:
`(LocalDb)\v11.0`
to
`(LocalDB)\MSSQLLocalDB`

Hopefully this saves someone some time.
